vim.o.sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
vim.g.have_nerd_font = true -- Enables NERD font support
vim.g.mapleader = " " -- Sets the leader key to space
vim.g.maplocalleader = "\\" -- Sets the local leader key to backslash

vim.opt.autoindent = true -- Enables automatic indentation
vim.opt.background = "dark" -- Sets the background theme to dark
vim.opt.breakindent = true -- Preserves indentation in wrapped lines
vim.opt.clipboard = "unnamedplus" -- Uses the system clipboard for all operations
vim.opt.cmdheight = 0 -- Sets the command line height to 0 (no command line)
vim.opt.confirm = true -- Asks for confirmation when closing unsaved files
vim.opt.cursorline = true -- Highlights the line with the cursor
vim.opt.cursorcolumn = true -- Highlights the column with the cursor
vim.opt.expandtab = true -- Converts tabs to spaces
vim.opt.fileencoding = "utf-8" -- Sets the file encoding to UTF-8
vim.opt.foldenable = true -- Enables code folding
vim.opt.foldlevel = 99 -- Sets the fold level to 99, effectively unfolding all folds
vim.opt.foldlevelstart = 99 -- Starts with all folds open
vim.opt.hidden = true -- Allows switching buffers without saving
vim.opt.hlsearch = true -- Highlights search results
vim.opt.ignorecase = false -- Ignores case in search patterns
vim.opt.inccommand = "split" -- Shows the effects of a command incrementally in a split window
vim.opt.incsearch = true -- Shows search matches as you type
vim.opt.laststatus = 3 -- Always shows the status line
vim.opt.linebreak = true -- Breaks lines at word boundaries
vim.opt.list = true -- Shows whitespace characters
vim.opt.listchars = { tab = "» ", trail = "·", nbsp = "␣" } -- Sets symbols for whitespace characters
vim.opt.mouse = "a" -- Enables mouse support in all modes
vim.opt.mousemoveevent = true -- Enables mouse move events
vim.opt.number = true -- Shows line numbers
vim.opt.relativenumber = true -- Shows relative line numbers
vim.opt.scrolloff = 5 -- Keeps lines visible above and below the cursor
vim.opt.shiftwidth = 4 -- Sets the number of spaces for each indentation level
vim.opt.showmatch = true -- Highlights matching parentheses
vim.opt.showmode = false -- Hides the mode display (e.g., -- INSERT --)
vim.opt.smartcase = true -- Overrides ignorecase if search pattern contains uppercase letters
vim.opt.smartindent = true -- Makes indenting smart
vim.opt.smarttab = true -- Makes tabbing smarter
vim.opt.softtabstop = 4 -- Sets the number of spaces a tab counts for in insert mode
vim.opt.splitbelow = true -- Forces horizontal splits to go below current window
vim.opt.splitright = true -- Forces vertical splits to go to the right of current window
vim.opt.statuscolumn = "%s %{v:lnum} %{v:relnum} "
vim.opt.tabstop = 4 -- Sets the number of spaces a tab counts for
vim.opt.termguicolors = true -- Enables 24-bit RGB color in the TUI
vim.opt.timeoutlen = 1000 -- Sets the time to wait for a mapped sequence to complete
vim.opt.ttyfast = true -- Assumes a fast terminal connection
vim.opt.undofile = true -- Enables persistent undo
vim.opt.updatetime = 250 -- Sets the time for writing swap file and triggering CursorHold
vim.opt.wildmode = "longest,list" -- Command-line completion mode
vim.opt.winblend = 25 -- Sets the window blend for transparency
